### ISSUE TITLE
请问最优化往年题的密码是什么？

### ISSUE THREAD

**Issue by sherpahu** [Huntersxsx/SJTU_2020_Spring#1]
![image](https://user-images.githubusercontent.com/30852287/133008890-e4a9cdce-e401-4b8a-b4a2-09b128c07a80.png)

**Comment by Huntersxsx** [comment]
试试看 2019-2020

**Comment by Huntersxsx** [comment]
试试看 2019-2020

**Comment by Huntersxsx** [comment]
@sherpahu 试试看 2019-2020

**Comment by sherpahu** [comment]
万分感谢
